# Generated by Django 5.1.3 on 2024-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_conj', models.CharField(max_length=100)),
                ('fr_conj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subj',
            fields=[
                ('subj_id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_subj', models.CharField(max_length=50)),
                ('fr_subj', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'subj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('tense_id', models.AutoField(primary_key=True, serialize=False)),
                ('tense_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('verb_id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_inf', models.CharField(max_length=100)),
                ('fr_inf', models.CharField(max_length=100)),
                ('group', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'verb',
                'managed': False,
            },
        ),
    ]
